import type { Job } from "./types";

export const STUDENT = {
  name: "Gabriel Ribeiro",
  firstName: "Gabriel",
  initials: "GR",
  email: "gabriel.ribeiro@gea.inatel.br",
  course: "Engenharia de Software",
  period: 5,
  registration: "20231234",
};

export const JOBS: Job[] = [
  {
    id: 1,
    title: "Estágio em Desenvolvimento Front-end",
    company: "Inatel Competence Center",
    companyCode: "in",
    companyTone: "blue",
    location: "Santa Rita do Sapucaí, MG",
    mode: "Híbrido",
    deadline: "15 jul",
    course: "Engenharia de Software",
    minPeriod: 2,
    type: "Estágio",
    isNew: true,
    description:
      "Você vai apoiar o desenvolvimento de interfaces web responsivas para produtos de telecomunicações, colaborando com um time multidisciplinar de produto.",
    requirements: [
      "Cursando Engenharia de Software ou Computação",
      "A partir do 2º período",
      "React e fundamentos de JavaScript",
      "Boa comunicação e vontade de aprender",
    ],
  },
  {
    id: 2,
    title: "Estágio em Dados e Relatórios",
    company: "Ericsson",
    companyCode: "E",
    companyTone: "navy",
    location: "Santa Rita do Sapucaí, MG",
    mode: "Remoto",
    deadline: "18 jul",
    course: "Engenharia de Software",
    minPeriod: 3,
    type: "Estágio",
    isNew: true,
    description:
      "Apoie análises de dados, automações e painéis de acompanhamento para soluções de redes de próxima geração.",
    requirements: ["Python básico", "Interesse por dados e dashboards", "A partir do 3º período"],
  },
  {
    id: 3,
    title: "Desenvolvedor(a) Mobile Jr.",
    company: "Zup Innovation",
    companyCode: "ZUP",
    companyTone: "light",
    location: "São Paulo, SP",
    mode: "Remoto",
    deadline: "22 jul",
    course: "Engenharia de Software",
    minPeriod: 5,
    type: "Júnior",
    description:
      "Participe da construção de experiências mobile de alta escala em uma equipe com forte cultura de engenharia e colaboração.",
    requirements: ["React Native ou Flutter", "Git e APIs REST", "Disponibilidade de 30 horas semanais"],
  },
  {
    id: 4,
    title: "Estágio em Segurança Cibernética",
    company: "Vivo",
    companyCode: "V",
    companyTone: "violet",
    location: "São Paulo, SP",
    mode: "Híbrido",
    deadline: "25 jul",
    course: "Engenharia de Computação",
    minPeriod: 4,
    type: "Estágio",
    description:
      "Acompanhe indicadores de segurança, documente incidentes e contribua com melhorias de proteção para serviços digitais.",
    requirements: ["Redes de computadores", "Linux básico", "A partir do 4º período"],
  },
  {
    id: 5,
    title: "Estágio em Produto Digital",
    company: "Take Blip",
    companyCode: "TB",
    companyTone: "teal",
    location: "Belo Horizonte, MG",
    mode: "Remoto",
    deadline: "30 jul",
    course: "Engenharia de Software",
    minPeriod: 2,
    type: "Estágio",
    description:
      "Ajude a investigar necessidades de usuários e a evoluir experiências digitais junto a design, produto e engenharia.",
    requirements: ["Interesse por produtos digitais", "Organização", "Boa comunicação escrita"],
  },
];
